### ISSUE TITLE
Multiple parents of a role?

### ISSUE THREAD

**Issue by olegkrivtsov** [zendframework/zend-permissions-rbac#22] opened 2016-12-10 08:09 UTC
I'm trying to use `Rbac` in my website. I found that the `Rbac::addRole()` method accepts `$parents` argument, which can be the list of parent roles of the role being added. But, the `Role` can have a single parent only (as I see from code of `Role` and `AbstractRole`). If we pass several roles as `$parents` argument, each parent role will be assigned a child, but since the child is the same (it is not cloned), this results in incorrect assignment of the `$parent` property of the child role. It seems that this doesn't affect the way the `Rbac::isGranted()` works, but the design is incorrect, I suspect. Either remove `getParent()` method from role, or do not allow to assign multiple parents.

**Comment by ezimuel** [comment] 2016-12-14 17:37
@olegkrivtsov do you have any test ready for this behaviour? I would like to fix this before the next minor release 2.6.0 that will include #21. Thanks.

**Comment by weierophinney** [comment] 2016-12-14 18:31
I would argue that `$parent` should be an array/aggregate of all parent roles.

This has implications for `getParent()`, however:

- If we modify `$parent` to allow an `array`, `getParent()` can then return an `array`, which could potentially be problematic in terms of behavior (as `null` or `RoleInterface` was assumed previously). As it is, currently, users need to check for `$parent`, and, ideally, are checking against either `null` or `RoleInterface`; however, if they did something like:

  ```php
  $parent = $role->getParent();
  if (! $parent) {
      return;
  }
  echo $parent->getName();
  ````

  The above would now be problematic if an array were returned, as it would fail the condition, and we'd now have method access on an array leading to an error.

- Alternately, we could define an "aggregate" class that would compose all parent roles, but implement `RoleInterface`. The problem with this approach is that methods such as `getName()` have no immediately understandable meaning.

In most cases, I think the point is moot, since textual roles will be used, which results in many discrete instances of `Role` vs identical (cloned) instances — which is why `isGranted()` continues to work fine.

My inclination is to allow another return type, `array`, to `getParent()`. However, because of the problems mentioned above, I also think that this would require a major version bump to ensure consumer code does not break.

**Comment by olegkrivtsov** [comment] 2016-12-15 02:06
@ezimuel here is an example. Assume we have a Blog app with four roles: Administrator, Manager, Editor and Viewer. Manager inherits permissions from Viewer and Editor. Administrator inherits permissions from Manager.

```php
$rbac = new Rbac();
$this->rbac = $rbac;
                       
$adminRole = new RbacRole('Administrator');
$adminRole->addPermission('user.manage');
$rbac->addRole($adminRole, ['Manager']);
        
$managerRole = new RbacRole('Manager');
$managerRole->addPermission('post.publish');
$rbac->addRole($managerRole, ['Viewer', 'Editor']);
        
$viewerRole = new RbacRole('Viewer');
$viewerRole->addPermission('post.view');
$rbac->addRole($viewerRole);
        
$editorRole = new RbacRole('Editor');
$editorRole->addPermission('post.edit');
$rbac->addRole($editorRole);
```

Actually, what stops a role from having multiple parents? Multiple roles can inherit permissions from other roles. So, here we have a "partially ordered tree" with multiple parents and multiple children, not a classic tree with single parent and multiple children.

**Comment by ezimuel** [comment] 2016-12-15 14:09
@olegkrivtsov, @weierophinney I analyzed the issue and this is definitely a bug. The issue doesn't affect the permissions because the relations are build correctly using the children nodes. The problem is only related to the specific `Zend\Permission\Rbac\AbstractRole::setParent()` and `Zend\Permission\Rbac\AbstractRole::getParent()` implementations. 
I'm working on a fix for this issue. We need to change the RoleInterface to manage array of parents and this will be a BC break (even if related to a bug). I think we can release it with 2.6.0.

**Comment by adrium** [comment] 2016-12-16 10:25
A while ago, I also noted that `setParent()` is not usable in the way one would expect... I would mark it as `@internal` or declare it as `protected`, and note that `addChild()` can be used which behaves correctly.

**Comment by olegkrivtsov** [comment] 2017-01-18 15:55
Any progress with this issue? I can implement the changes @weierophinney  requested and provide a pull request. Is this acceptable?

**Comment by ezimuel** [comment] 2018-01-29 17:17
@olegkrivtsov yes, I just added this PR in my todo list, thanks to the reminder #32. 
Please be sure to start from my #23 PR. I'll review it when it's ready.
Thanks!

**Comment by ezimuel** [comment] 2018-01-31 16:40
@olegkrivtsov I updated #23 with @weierophinney comments and we'll merge soon. Thanks anyway for your contribution!

**Closed** 2018-01-31 17:04 UTC
Labels: bug
